stages:
- quality
- build
- test
- release
- publish

# Default include
.default:
    only:
    - tags
    - merge_requests

    export CI_REGISTRY="git-registry.emico.nl"
    export CI_REGISTRY_IMAGE="$CI_REGISTRY/$CI_PROJECT_PATH"
    export CI_COMMIT_TAG=${CI_COMMIT_TAG:-latest}

.docker:
    variables:
        CI_REGISTRY: 'git-registry.emico.nl'
        CI_REGISTRY_IMAGE: "git-registry.emico.nl/$CI_PROJECT_PATH"
    before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" $CI_REGISTRY

include:
- '/gitlab/variables.yaml'
- '/gitlab/quality.yaml'
- '/gitlab/build.yaml'
- '/gitlab/release.yaml'
- '/gitlab/publish.yaml'
