services:
- docker:19.03.8-dind
image: git-registry.emico.nl/hipex-services/docker-image-build

stages:
- build
- test

.build:
    stage: build
    script:
    - build.sh --build-arg PHP_VERSION=$PHP_VERSION --build-arg IMAGE_VERSION=$VERSION .
    only:
    - tags
    - master

build:7.2-cli:
    extends: .build
    variables:
        PHP_VERSION: "7.2-cli"
        VERSION: "7.2-cli"

build:7.2-devel:
    extends: .build
    variables:
        PHP_VERSION: "7.2-cli"
        VERSION: "7.2-devel"

build:7.2-fpm:
    extends: .build
    variables:
        PHP_VERSION: "7.2-fpm"
        VERSION: "7.2-fpm"

build:7.3-cli:
    extends: .build
    variables:
        PHP_VERSION: "7.3-cli"
        VERSION: "7.3-cli"

build:7.3-devel:
    extends: .build
    variables:
        PHP_VERSION: "7.3-cli"
        VERSION: "7.3-devel"

build:7.3-fpm:
    extends: .build
    variables:
        PHP_VERSION: "7.3-fpm"
        VERSION: "7.3-fpm"

build:7.4-cli:
    extends: .build
    variables:
        PHP_VERSION: "7.4-cli"
        VERSION: "7.4-cli"

build:7.4-devel:
    extends: .build
    variables:
        PHP_VERSION: "7.4-cli"
        VERSION: "7.4-devel"

build:7.4-fpm:
    extends: .build
    variables:
        PHP_VERSION: "7.4-fpm"
        VERSION: "7.4-fpm"
