services:
- docker:19.03.8-dind

image: docker:19.03.8
variables:
    CI_REGISTRY: "https://git-registry.emico.nl"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY/$CI_PROJECT_PATH"
before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
- build
- test

.build:
    stage: build
    script:
    - build.sh --build-arg VERSION=$VERSION .
    only:
    - tags
    - master

build:7.2:
    extends: .build
    variables:
        VERSION: "7.2"

build:7.3:
    extends: .build
    variables:
        VERSION: "7.3"

build:7.4:
    extends: .build
    variables:
        VERSION: "7.4"
