image: git-registry.emico.nl/hipex-services/docker-image-build

stages:
- quality
- build
- test
- release
- publish

# Default include
.default:
    only:
    - tags
    - merge_requests

include:
- '/gitlab/variables.yaml'
- '/gitlab/quality.yaml'
- '/gitlab/build.yaml'
- '/gitlab/release.yaml'
- '/gitlab/publish.yaml'
