services:
- docker:19.03.8-dind
image: git-registry.emico.nl/hipex-services/docker-image-build

stages:
- build
- test

.build:
    stage: build
    script:
    - build.sh --build-arg VERSION=$VERSION .
    only:
    - tags
    - master

build:7.2:
    extends: .build
    variables:
        VERSION: "7.2"

build:7.3:
    extends: .build
    variables:
        VERSION: "7.3"

build:7.4:
    extends: .build
    variables:
        VERSION: "7.4"
