#######################
# Build stage
#######################
.build:
    image: docker:19.03.12
    services:
    - name: docker:19.03.12-dind
      command: ["--experimental"]
    extends:
    - .default
    - .docker
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
    stage: build
    script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" $CI_REGISTRY
    - docker pull "${CI_REGISTRY_IMAGE}:cache" || true
    - |
        docker build \
            --build-arg PHP_VERSION=$PHP_VERSION \
            --build-arg IMAGE_VERSION=${VERSION} \
            --cache-from "${CI_REGISTRY_IMAGE}/${VERSION}:cache" \
            --tag "${CI_REGISTRY_IMAGE}/${VERSION}:cache" \
            --tag "${CI_REGISTRY_IMAGE}/${VERSION}:${CI_COMMIT_SHA}" \
            .
    - docker push "${CI_REGISTRY_IMAGE}/${VERSION}:${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}/${VERSION}:cache"

# PHP 7.2
###########################
build:7.2-cli:
    extends:
    - .build
    - .7.2-cli

build:7.2-cli-devel:
    extends:
    - .build
    - .7.2-cli-devel

build:7.2-fpm:
    extends:
    - .build
    - .7.2-fpm

build:7.2-fpm-devel:
    extends:
    - .build
    - .7.2-fpm-devel

# PHP 7.3
###########################
build:7.3-cli:
    extends:
    - .build
    - .7.3-cli

build:7.3-cli-devel:
    extends:
    - .build
    - .7.3-cli-devel

build:7.3-fpm:
    extends:
    - .build
    - .7.3-fpm

build:7.3-fpm-devel:
    extends:
    - .build
    - .7.3-fpm-devel

# PHP 7.4
###########################
build:7.4-cli:
    extends:
    - .build
    - .7.4-cli

build:7.4-cli-devel:
    extends:
    - .build
    - .7.4-cli-devel

build:7.4-fpm:
    extends:
    - .build
    - .7.4-fpm

build:7.4-fpm-devel:
    extends:
    - .build
    - .7.4-fpm-devel
