#######################
# Build stage
#######################
.build:
    image: docker:19.03.12
    service:
    - name: docker:19.03.12-dind
      command: ["--experimental"]
    extends: .default
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
    stage: build
    script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" $CI_REGISTRY
    - docker pull "${CI_REGISTRY_IMAGE}:cache" || true
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:cache" --tag "${CI_REGISTRY_IMAGE}:cache" --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:cache"

# PHP 7.0
###########################
build:7.0-cli:
    extends:
    - .build
    - .7.0-cli

build:7.0-devel:
    extends:
    - .build
    - .7.0-devel

build:7.0-fpm:
    extends:
    - .build
    - .7.0-fpm

# PHP 7.1
###########################
build:7.1-cli:
    extends:
    - .build
    - .7.1-cli

build:7.1-devel:
    extends:
    - .build
    - .7.1-devel

build:7.1-fpm:
    extends:
    - .build
    - .7.1-fpm

# PHP 7.2
###########################
build:7.2-cli:
    extends:
    - .build
    - .7.2-cli

build:7.2-devel:
    extends:
    - .build
    - .7.2-devel

build:7.2-fpm:
    extends:
    - .build
    - .7.2-fpm

# PHP 7.3
###########################
build:7.3-cli:
    extends:
    - .build
    - .7.3-cli

build:7.3-devel:
    extends:
    - .build
    - .7.3-devel

build:7.3-fpm:
    extends:
    - .build
    - .7.3-fpm

# PHP 7.4
###########################
build:7.4-cli:
    extends:
    - .build
    - .7.4-cli

build:7.4-devel:
    extends:
    - .build
    - .7.4-devel

build:7.4-fpm:
    extends:
    - .build
    - .7.4-fpm
