name: Lint
on:
    pull_request:

jobs:
    #########################################################
    # Lint and style checks
    #########################################################
    quality_hadolint:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   uses: reviewdog/action-hadolint@v1
