name: Publish
on:
    release:
        types: [published]

jobs:
    #########################################################
    # Publish semver containers
    #########################################################
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                version: ["7.2", "7.3", "7.4", "8.0", "8.1"]
                image: ["cli", "fpm"]
                devel: ["", "-devel"]
        steps:
        -   uses: actions/checkout@v2
        -   uses: crazy-max/ghaction-docker-meta@v1
            id: docker_meta
            with:
                images: ghcr.io/hipexbv/container-base-php
                tag-semver: |
                    {{version}}
        -   uses: docker/setup-buildx-action@v1.0.4
        -   uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.ACCESS_TOKEN }}
        -   uses: actions/cache@v2
            with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-proxy-${{ matrix.version }}-${{ matrix.image }}-${{ github.sha }}-
                restore-keys: |
                    ${{ runner.os }}-buildx-proxy-${{ matrix.version }}-${{ matrix.image }}-
        -   uses: docker/build-push-action@v2.2.2
            with:
                context: .
                push: true
                tags: ghcr.io/hipexbv/container-base-php:${{ matrix.version }}-${{ matrix.image }}${{ matrix.devel }}-${{ steps.docker_meta.outputs.version }}
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
                build-args: |
                    PHP_VERSION=${{ matrix.version }}-${{ matrix.image }}
                    IMAGE_VERSION=${{ matrix.image }}${{ matrix.devel }}
