name: Release
on:
    push:
        branches:
        - main
        - master
        - alpha
        - beta

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
            with:
                persist-credentials: false
        -   uses: cycjimmy/semantic-release-action@v2
            with:
                semantic_version: 17
                extra_plugins: |
                    semantic-release-slack-bot
            env:
                GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
